[build]
publish: /opt/build/repo/build
functions = "./function/"
[[redirects]]
from = "/api"
to= "./netlify/functions/:splat"
status = 200
command: CI= npm run build
commandOrigin: ui
publishOrigin: ui